export enum REDIS_ENUM {
  EMAIL_VERIFICATION = 'CAMPUSCONNECTAUTH:EMAIL_VERIFICATION',
  USERNAME_AVAILABLE = 'CAMPUSCONNECTAUTH:USERNAME_AVAILABLE',
}
export enum REDIS_TTL_ENUM {
  FIVE_MINUTES = 300, // 5 minutes
  TEN_MINUTES = 600, // 10 minutes
  FIFTEEN_MINUTES = 900, // 15 minutes
  TWENTY_MINUTES = 1200, // 20 minutes
}
